Рендер для будущего триггера прыжка | Update ParticleController.java
Slomix/ParkourBeat pull request #108
Opened 2024-05-07 23:55 UTC by XaviersDev

2024-05-10 08:11 UTC, Dymeth commented
По какому принципу добавляются частицы в список, если самих триггеров прыжка пока нет?

2024-05-10 10:20 UTC, DrupalDoesNotExists requested changes

2024-05-10 15:38 UTC, XaviersDev commented on src/main/java/ru/sortix/parkourbeat/levels/ParticleController.java
> +                        Location particleLocation = currentPoint.getLocation().clone().add(0.3 * Math.cos(j * Math.PI / 2), 0, 0.3 * Math.sin(j * Math.PI / 2));
Да, я же тестировал.

2024-05-11 12:22 UTC, Dymeth commented on src/main/java/ru/sortix/parkourbeat/levels/ParticleController.java
> +                        Location particleLocation = currentPoint.getLocation().clone().add(0.3 * Math.cos(j * Math.PI / 2), 0, 0.3 * Math.sin(j * Math.PI / 2));
> Да, я же тестировал.

Речь не о том, работает ли код. А о том, насколько оптимальное это решение с точки зрения производительности.
Лично я тут не вижу никакой проблемы, поскольку частицы кэшируются в оперативке. Однако смысла в таких расчётах не вижу тоже

2024-05-11 12:30 UTC, Dymeth commented on src/main/java/ru/sortix/parkourbeat/levels/ParticleController.java
> +                if (i == 0 && height > 0) {
Для чего тут проверка на то, что это первая точка?

2024-05-12 15:36 UTC, XaviersDev commented on src/main/java/ru/sortix/parkourbeat/levels/ParticleController.java
> +                if (i == 0 && height > 0) {
> Для чего тут проверка на то, что это первая точка?

А что? Ставить рендер на двух точках? Это будет бессмысленно, ведь игрок будет второй раз прыгать.

2024-05-12 15:36 UTC, XaviersDev commented on src/main/java/ru/sortix/parkourbeat/levels/ParticleController.java
> +                        Location particleLocation = currentPoint.getLocation().clone().add(0.3 * Math.cos(j * Math.PI / 2), 0, 0.3 * Math.sin(j * Math.PI / 2));
> > Да, я же тестировал.
> 
> Речь не о том, работает ли код. А о том, насколько оптимальное это решение с точки зрения производительности. Лично я тут не вижу никакой проблемы, поскольку частицы кэшируются в оперативке. Однако смысла в таких расчётах не вижу тоже

Тогда это нужно исправлять, но я не знаю как.

2024-05-13 06:13 UTC, Dymeth commented on src/main/java/ru/sortix/parkourbeat/levels/ParticleController.java
> +                if (i == 0 && height > 0) {
> > Для чего тут проверка на то, что это первая точка?
> 
> А что? Ставить рендер на двух точках? Это будет бессмысленно, ведь игрок будет второй раз прыгать.

Частицы должны отображаться перед абсолютно всеми прыжками на уровне

2024-09-06 13:30 UTC, closed without merging

2024-09-06 13:30 UTC, Dymeth commented
Уже давно добавлена визуализация прыжков на базе кода из этого PR. Спасибо за помощь!
https://github.com/Slomix/ParkourBeat/commit/0a002b42498760450f7a01b6f9f99bcd38bb78e0
https://github.com/Slomix/ParkourBeat/commit/3182b72764fab61dcaf367f048a198cc0966072e