Update README.MD
Slomix/ParkourBeat pull request #111
Opened 2024-05-18 12:41 UTC by AlliSite

2024-05-18 14:30 UTC, Dymeth requested changes

2024-05-18 14:30 UTC, Dymeth commented on README.MD
> +![image](https://private-user-images.githubusercontent.com/122743694/331800645-218ce2dc-a9e1-4c57-af10-3b185881877d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicm
Изображение недоступно

2024-05-23 16:24 UTC, AlliSite commented
![image](https://github.com/Slomix/ParkourBeat/assets/122743694/d58537eb-9f64-4d28-a65a-bca6dbc54b23)

2024-09-06 13:33 UTC, Dymeth commented
Изображение необходимо загрузить в репозиторий и дать на него ссылку в README. Без этого корректно работать не будет.
Поскольку обновлений давно не было - пока закрываю

2024-09-06 13:33 UTC, closed without merging